language: node_js
node_js:
  # Select a Node version where there if a Fibers binary available.
  - 8.11.1
branches:
  only:
    - master
cache:
  directories:
  - node_modules/
script:
  - npm run lint
  - npm run test
